/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WorkspaceDeletedRouteImport } from './routes/workspace-deleted'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTriageRouteImport } from './routes/_app/triage'
import { Route as AppIInteractionIdRouteImport } from './routes/_app/i.$interactionId'
import { Route as AppOObjectRouteImport } from './routes/_app/o.$object'
import { Route as AppRRecordIdRouteImport } from './routes/_app/r.$recordId'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings.index'
import { Route as AppSettingsAccessRouteImport } from './routes/_app/settings.access'
import { Route as AppSettingsDraftingRouteImport } from './routes/_app/settings.drafting'
import { Route as AppSettingsSchemaRouteImport } from './routes/_app/settings.schema'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings.team'
import { Route as AppSettingsTriageRouteImport } from './routes/_app/settings.triage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceDeletedRoute = WorkspaceDeletedRouteImport.update({
  id: '/workspace-deleted',
  path: '/workspace-deleted',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppIInteractionIdRoute = AppIInteractionIdRouteImport.update({
  id: '/i/$interactionId',
  path: '/i/$interactionId',
  getParentRoute: () => AppRoute,
} as any)
const AppOObjectRoute = AppOObjectRouteImport.update({
  id: '/o/$object',
  path: '/o/$object',
  getParentRoute: () => AppRoute,
} as any)
const AppRRecordIdRoute = AppRRecordIdRouteImport.update({
  id: '/r/$recordId',
  path: '/r/$recordId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAccessRoute = AppSettingsAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDraftingRoute = AppSettingsDraftingRouteImport.update({
  id: '/drafting',
  path: '/drafting',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSchemaRoute = AppSettingsSchemaRouteImport.update({
  id: '/schema',
  path: '/schema',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsTriageRoute = AppSettingsTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/workspace-deleted': typeof WorkspaceDeletedRoute
  '/connections': typeof AppConnectionsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/triage': typeof AppTriageRoute
  '/i/$interactionId': typeof AppIInteractionIdRoute
  '/o/$object': typeof AppOObjectRoute
  '/r/$recordId': typeof AppRRecordIdRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/drafting': typeof AppSettingsDraftingRoute
  '/settings/schema': typeof AppSettingsSchemaRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/triage': typeof AppSettingsTriageRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/workspace-deleted': typeof WorkspaceDeletedRoute
  '/connections': typeof AppConnectionsRoute
  '/triage': typeof AppTriageRoute
  '/': typeof AppIndexRoute
  '/i/$interactionId': typeof AppIInteractionIdRoute
  '/o/$object': typeof AppOObjectRoute
  '/r/$recordId': typeof AppRRecordIdRoute
  '/settings/access': typeof AppSettingsAccessRoute
  '/settings/drafting': typeof AppSettingsDraftingRoute
  '/settings/schema': typeof AppSettingsSchemaRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/triage': typeof AppSettingsTriageRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/workspace-deleted': typeof WorkspaceDeletedRoute
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/triage': typeof AppTriageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/i/$interactionId': typeof AppIInteractionIdRoute
  '/_app/o/$object': typeof AppOObjectRoute
  '/_app/r/$recordId': typeof AppRRecordIdRoute
  '/_app/settings/access': typeof AppSettingsAccessRoute
  '/_app/settings/drafting': typeof AppSettingsDraftingRoute
  '/_app/settings/schema': typeof AppSettingsSchemaRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/settings/triage': typeof AppSettingsTriageRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workspace-deleted'
    | '/connections'
    | '/settings'
    | '/triage'
    | '/i/$interactionId'
    | '/o/$object'
    | '/r/$recordId'
    | '/settings/access'
    | '/settings/drafting'
    | '/settings/schema'
    | '/settings/team'
    | '/settings/triage'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/workspace-deleted'
    | '/connections'
    | '/triage'
    | '/'
    | '/i/$interactionId'
    | '/o/$object'
    | '/r/$recordId'
    | '/settings/access'
    | '/settings/drafting'
    | '/settings/schema'
    | '/settings/team'
    | '/settings/triage'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/workspace-deleted'
    | '/_app/connections'
    | '/_app/settings'
    | '/_app/triage'
    | '/_app/'
    | '/_app/i/$interactionId'
    | '/_app/o/$object'
    | '/_app/r/$recordId'
    | '/_app/settings/access'
    | '/_app/settings/drafting'
    | '/_app/settings/schema'
    | '/_app/settings/team'
    | '/_app/settings/triage'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WorkspaceDeletedRoute: typeof WorkspaceDeletedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace-deleted': {
      id: '/workspace-deleted'
      path: '/workspace-deleted'
      fullPath: '/workspace-deleted'
      preLoaderRoute: typeof WorkspaceDeletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/i/$interactionId': {
      id: '/_app/i/$interactionId'
      path: '/i/$interactionId'
      fullPath: '/i/$interactionId'
      preLoaderRoute: typeof AppIInteractionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$object': {
      id: '/_app/o/$object'
      path: '/o/$object'
      fullPath: '/o/$object'
      preLoaderRoute: typeof AppOObjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$recordId': {
      id: '/_app/r/$recordId'
      path: '/r/$recordId'
      fullPath: '/r/$recordId'
      preLoaderRoute: typeof AppRRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/access': {
      id: '/_app/settings/access'
      path: '/access'
      fullPath: '/settings/access'
      preLoaderRoute: typeof AppSettingsAccessRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/drafting': {
      id: '/_app/settings/drafting'
      path: '/drafting'
      fullPath: '/settings/drafting'
      preLoaderRoute: typeof AppSettingsDraftingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/schema': {
      id: '/_app/settings/schema'
      path: '/schema'
      fullPath: '/settings/schema'
      preLoaderRoute: typeof AppSettingsSchemaRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/triage': {
      id: '/_app/settings/triage'
      path: '/triage'
      fullPath: '/settings/triage'
      preLoaderRoute: typeof AppSettingsTriageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsAccessRoute: typeof AppSettingsAccessRoute
  AppSettingsDraftingRoute: typeof AppSettingsDraftingRoute
  AppSettingsSchemaRoute: typeof AppSettingsSchemaRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsTriageRoute: typeof AppSettingsTriageRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAccessRoute: AppSettingsAccessRoute,
  AppSettingsDraftingRoute: AppSettingsDraftingRoute,
  AppSettingsSchemaRoute: AppSettingsSchemaRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsTriageRoute: AppSettingsTriageRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIInteractionIdRoute: typeof AppIInteractionIdRoute
  AppOObjectRoute: typeof AppOObjectRoute
  AppRRecordIdRoute: typeof AppRRecordIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
  AppIInteractionIdRoute: AppIInteractionIdRoute,
  AppOObjectRoute: AppOObjectRoute,
  AppRRecordIdRoute: AppRRecordIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WorkspaceDeletedRoute: WorkspaceDeletedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
