/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConnectionsRouteImport } from './routes/_app/connections'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTriageRouteImport } from './routes/_app/triage'
import { Route as AppIInteractionIdRouteImport } from './routes/_app/i.$interactionId'
import { Route as AppOObjectRouteImport } from './routes/_app/o.$object'
import { Route as AppRRecordIdRouteImport } from './routes/_app/r.$recordId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppIInteractionIdRoute = AppIInteractionIdRouteImport.update({
  id: '/i/$interactionId',
  path: '/i/$interactionId',
  getParentRoute: () => AppRoute,
} as any)
const AppOObjectRoute = AppOObjectRouteImport.update({
  id: '/o/$object',
  path: '/o/$object',
  getParentRoute: () => AppRoute,
} as any)
const AppRRecordIdRoute = AppRRecordIdRouteImport.update({
  id: '/r/$recordId',
  path: '/r/$recordId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/connections': typeof AppConnectionsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/triage': typeof AppTriageRoute
  '/i/$interactionId': typeof AppIInteractionIdRoute
  '/o/$object': typeof AppOObjectRoute
  '/r/$recordId': typeof AppRRecordIdRoute
}
export interface FileRoutesByTo {
  '/connections': typeof AppConnectionsRoute
  '/search': typeof AppSearchRoute
  '/settings': typeof AppSettingsRoute
  '/triage': typeof AppTriageRoute
  '/': typeof AppIndexRoute
  '/i/$interactionId': typeof AppIInteractionIdRoute
  '/o/$object': typeof AppOObjectRoute
  '/r/$recordId': typeof AppRRecordIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/connections': typeof AppConnectionsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/': typeof AppIndexRoute
  '/_app/i/$interactionId': typeof AppIInteractionIdRoute
  '/_app/o/$object': typeof AppOObjectRoute
  '/_app/r/$recordId': typeof AppRRecordIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/search'
    | '/settings'
    | '/triage'
    | '/i/$interactionId'
    | '/o/$object'
    | '/r/$recordId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connections'
    | '/search'
    | '/settings'
    | '/triage'
    | '/'
    | '/i/$interactionId'
    | '/o/$object'
    | '/r/$recordId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/connections'
    | '/_app/search'
    | '/_app/settings'
    | '/_app/triage'
    | '/_app/'
    | '/_app/i/$interactionId'
    | '/_app/o/$object'
    | '/_app/r/$recordId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connections': {
      id: '/_app/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/i/$interactionId': {
      id: '/_app/i/$interactionId'
      path: '/i/$interactionId'
      fullPath: '/i/$interactionId'
      preLoaderRoute: typeof AppIInteractionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/o/$object': {
      id: '/_app/o/$object'
      path: '/o/$object'
      fullPath: '/o/$object'
      preLoaderRoute: typeof AppOObjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/r/$recordId': {
      id: '/_app/r/$recordId'
      path: '/r/$recordId'
      fullPath: '/r/$recordId'
      preLoaderRoute: typeof AppRRecordIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTriageRoute: typeof AppTriageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIInteractionIdRoute: typeof AppIInteractionIdRoute
  AppOObjectRoute: typeof AppOObjectRoute
  AppRRecordIdRoute: typeof AppRRecordIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConnectionsRoute: AppConnectionsRoute,
  AppSearchRoute: AppSearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTriageRoute: AppTriageRoute,
  AppIndexRoute: AppIndexRoute,
  AppIInteractionIdRoute: AppIInteractionIdRoute,
  AppOObjectRoute: AppOObjectRoute,
  AppRRecordIdRoute: AppRRecordIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
